import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     

      
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1 className="boldercolor">CODE HUNTER</h1>
        </div>
          <Image className={styles.myImg} src="/homez.jpg" width={237} height={150}/>


        <p className={styles.homedescrip}>A Blog for hunting coder for hunting code </p>

        <div className={styles.popular__blog}>
          <h2>Popular blogs</h2>

          <div className={styles.blogslot}>
            <h3>How to learn js in 2023 ? </h3>
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod,
              ex.
            </p>
          </div>
          <div className={styles.blogslot}>
            <h3>How to learn js in 2023 ? </h3>
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod,
              ex.
            </p>
          </div>
          <div className={styles.blogslot}>
            <h3>How to learn js in 2023 ? </h3>
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod,
              ex.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
